				<article class="container">
					<h2>Subir imagen</h2>
					<div class="cajaNoGusta">
					<ul id="ejer_2">
                        <li>
                            <form action="<?php _H($data['action'])?>" method="POST" enctype="multipart/form-data">
								<label>Imagen</label> 
								<br/>
								<input type="file" name="fichero_usuario" required="required" accept="image/*" onchange="loadFile(event)"/>
								<br/>
								<input type="submit" value="Enviar">
								<input type="reset" value="Deshacer">       
							</form>
                        </li>
                        <li>
                            <img id="output" style="max-width: 100%;max-height: 150px;">
                        </li>
                    </ul>
 					</div>
				</article>
