<article class="container">
    <h2> <?php _H($data['subtitulo'])?> </h2>
    <form action="<?php _H($data['action'])?>" method="POST">
        <fieldset>
            <label>Nuevo email</label> 
            <br/>
            <input type="email" name="email" class="item_requerid" size="25" maxlength="50" required="required" />
        </fieldset>
        <input type="submit" value="Enviar">      
    </form>
</article>
