            <article class="container">
                <h2> <?php _H($data["subtitulo"])?> </h2> 
                <table>
                    <?php if (!empty($rows)) {?>
                        <?php foreach($rows as  $row) {?>
                            <?php foreach($row as  $key=>$val) {?>
                                <tr><td><?php _H($key); echo(": ") ;_H($val); ?></td></tr>
                            <?php }?>
                            <tr>
                                <td><a href="<?php _H('?modulo=admin&peticion=delete_chiste&titulo='.$row["titulo"]);?>" >Borrar </a></td>
                            </tr>
                        <?php }?>
                    <?php }?>
                 </table>
             </article>