				<article class="container">
					<h2>Buscar usuario</h2>
					<form action="<?php _H($data['action']);?>" method="POST" enctype="multipart/form-data">
						<fieldset>
							<label>Nombre de usuario</label> 
							<br/>
							<input type="text" name="nombre" size="25" maxlength="50" required="required" />
						</fieldset>
						<input type="submit" value="Enviar">
						<input type="reset" value="Deshacer">       
					</form>
				</article>