				<article class="container">
					<h2>Nuevo usuario</h2>
 					<form action="<?php _H($data['action'])?>" method="POST" enctype="multipart/form-data">
    				<fieldset>
						<label>Nombre Usuario</label> <br/>
						<input type="text" name="nombre" size="25" maxlength="50" placeholder="Nombre de usuario" required="required" /> 
						<br/>
						<label>Contraseña</label> <br/>
						<input type="password" name="contrasenya" size="25" maxlength="25" placeholder="Contraseña" required="required" />
						<br/>
						<label>Repite contraseña</label> <br/>
						<input type="password" name="contrasenya2" size="25" maxlength="25" placeholder="Contraseña" required="required" />
						<br/>
						<label for="email">Email</label> <br/>
						<input type="email" name="email" size="25" maxlength="50" placeholder="pp@pp.pp" required="required" /> 
						<br/>		  
					</fieldset>
					<input type="submit" value="Enviar">
					<input type="reset" value="Deshacer">       
					</form>
				</article>
