			<article class="container">
				<h2><?php _H($data["subtitulo"])?></h2>
				  
				<table>
					<?php if (!empty($rows)) {?>
						<?php foreach ($rows[0] as $key => $value) {?>
					  		<th><?php _H($key); ?></th>
					  	<?php }?>
					  	
					  	<?php foreach($rows as  $row) {?>
							<tr>
								<?php foreach($row as  $key => $val) {?>
						        	<td> <?php _H($val); ?></td>
						        <?php }?>   
						        <td><a href="<?php _H('?modulo=admin&peticion=delete_chiste&titulo='.$row["titulo"]);?>" >Borrar </a></td>
					        </tr>
					    <?php }?>
					<?php }?>
				</table>
			</article>
 
