        <div class="main">
        	<nav>
				<ul class="menuUserAdmin">
        			<li><span>usuario</span></li>
        			<li><a href="?modulo=admin&peticion=create_usuario">Añadir usuario</a></li>
                    <li><a href="?modulo=admin&peticion=lista_usuarios">Lista usuarios</a></li>
                    <li><a href="?modulo=admin&peticion=buscar_usuario">Buscar usuario</a></li>
        			<li><span>Chiste</span></li>
        			<li><a href="?modulo=admin&peticion=lista_chistes">Lista chistes</a></li>
                    <li><a href="?modulo=admin&peticion=buscar_chiste">Buscar chiste</a></li>
        			<li><span>Imagen</span></li>
                    <li><a href="?modulo=admin&peticion=lista_imagenes">Lista imágenes</a></li>
                    <li><a href="?modulo=admin&peticion=buscar_imagen">Buscar imágen</a></li>
   				</ul>
			</nav>  