        <div class="main">
        	<nav>
				<ul class="menuUserAdmin">
        			<li><span>Perfil</span></li>
        			<li><a href="?modulo=user&peticion=perfil">Mi perfil</a></li>
        			<li><span>Chiste</span></li>
        			<li><a href="?modulo=user&peticion=lista_chistes">Mis chistes</a></li>
        			<li><a href="?modulo=user&peticion=create_chiste">Añadir chiste</a></li>
        			<li><span>Imagen</span></li>
        			<li><a href="?modulo=user&peticion=lista_imagenes">Mis imágenes</a></li>
        			<li><a href="?modulo=user&peticion=create_imagen">Añadir imagen</a></li>
   				</ul>
			</nav>  