            <aside>
                <span>Zona de ocio :)</span><br/>
                <audio src="audio/gatoMusic.m4a" controls></audio>
                <canvas id="canvas">
                	Tu navegador no soporta canvas. ¡Actualízalo! <a href="https://www.google.es/chrome/browser/desktop/">Descargar Google Chrome</a>
                </canvas>
            </aside>
        </div><!--  Div main-->

        <footer class="footer default-primary-color">&copy;Copyright 2016</footer>

    </body>
</html>